# Generated by Django 3.2 on 2022-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date_released',
            field=models.DateField(default=None),
        ),
    ]
