# Generated by Django 3.2 on 2022-09-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_date_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albumName',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='albumName',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songName',
            new_name='song_name',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.artist'),
        ),
    ]
