# Generated by Django 3.2 on 2022-09-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_date_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_name',
        ),
    ]
